# Use an official Nginx image as the base image
FROM nginx:1.25.4

# Remove any existing config files
RUN rm /etc/nginx/conf.d/*

# Copy the custom Nginx configuration
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for Nginx
EXPOSE 80