# Dockerfile para rodar o servidor de desenvolvimento local, sem nginx
# $ cd website
# $ docker build -t 15-website-localserver -f Dockerfile.dev .
# $ docker run --name 15-website -p 3000:3000 -v "$(pwd):/website" 15-website-localserver
# acesso em http://localhost:3000 ou http://127.0.0.1:3000	

# se não tiver node_modules, precisa entrar no container e rodar npm install
# $ docker run -it --name 15-website -p 3000:3000 -v "$(pwd):/website" 15-website-localserver ash
# /website # npm install
# /website # npm start



# Use an official Node.js runtime as the base image
FROM node:16.17.0

# Set the working directory within the container
WORKDIR /website

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Adiciona a definição do volume
VOLUME ["/website"]

# Copy the rest of the application code to the container
COPY . .

# Start the server to serve the React app
CMD ["npm", "start"]

# Expose the port (assumindo que o servidor Node.js usa a porta 3000)
EXPOSE 3000